/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : number,
}
export type MenuItemId = bigint;
export interface Reservation {
  'id' : ReservationId,
  'customerName' : string,
  'status' : string,
  'date' : string,
  'time' : string,
  'tableId' : TableId,
  'notes' : string,
  'partySize' : bigint,
}
export type ReservationId = bigint;
export interface Room { 'id' : RoomId, 'name' : string }
export type RoomId = bigint;
export interface Table {
  'id' : TableId,
  'height' : number,
  'posX' : number,
  'posY' : number,
  'shape' : string,
  'capacity' : bigint,
  'roomId' : RoomId,
  'width' : number,
  'tableLabel' : string,
}
export type TableId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMenuItem' : ActorMethod<
    [string, string, number, string, boolean],
    MenuItemId
  >,
  'createReservation' : ActorMethod<
    [TableId, string, string, string, bigint, string],
    ReservationId
  >,
  'createRoom' : ActorMethod<[string], RoomId>,
  'createTable' : ActorMethod<
    [RoomId, string, string, bigint, number, number, number, number],
    TableId
  >,
  'deleteMenuItem' : ActorMethod<[MenuItemId], undefined>,
  'deleteReservation' : ActorMethod<[ReservationId], undefined>,
  'deleteRoom' : ActorMethod<[RoomId], undefined>,
  'deleteTable' : ActorMethod<[TableId], undefined>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getAllRooms' : ActorMethod<[], Array<Room>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[MenuItemId], [] | [MenuItem]>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getReservation' : ActorMethod<[ReservationId], [] | [Reservation]>,
  'getReservationsByDate' : ActorMethod<[string], Array<Reservation>>,
  'getReservationsByTable' : ActorMethod<[TableId], Array<Reservation>>,
  'getRoom' : ActorMethod<[RoomId], [] | [Room]>,
  'getTable' : ActorMethod<[TableId], [] | [Table]>,
  'getTablesByRoom' : ActorMethod<[RoomId], Array<Table>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMenuItem' : ActorMethod<
    [MenuItemId, string, string, number, string, boolean],
    undefined
  >,
  'updateReservation' : ActorMethod<
    [ReservationId, TableId, string, string, string, bigint, string, string],
    undefined
  >,
  'updateRoom' : ActorMethod<[RoomId, string], undefined>,
  'updateTable' : ActorMethod<
    [TableId, RoomId, string, string, bigint, number, number, number, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];