/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MenuItemId = IDL.Nat;
export const TableId = IDL.Nat;
export const ReservationId = IDL.Nat;
export const RoomId = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Reservation = IDL.Record({
  'id' : ReservationId,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'tableId' : TableId,
  'notes' : IDL.Text,
  'partySize' : IDL.Nat,
});
export const Room = IDL.Record({ 'id' : RoomId, 'name' : IDL.Text });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Table = IDL.Record({
  'id' : TableId,
  'height' : IDL.Float64,
  'posX' : IDL.Float64,
  'posY' : IDL.Float64,
  'shape' : IDL.Text,
  'capacity' : IDL.Nat,
  'roomId' : RoomId,
  'width' : IDL.Float64,
  'tableLabel' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Bool],
      [MenuItemId],
      [],
    ),
  'createReservation' : IDL.Func(
      [TableId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [ReservationId],
      [],
    ),
  'createRoom' : IDL.Func([IDL.Text], [RoomId], []),
  'createTable' : IDL.Func(
      [
        RoomId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [TableId],
      [],
    ),
  'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
  'deleteReservation' : IDL.Func([ReservationId], [], []),
  'deleteRoom' : IDL.Func([RoomId], [], []),
  'deleteTable' : IDL.Func([TableId], [], []),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getReservation' : IDL.Func(
      [ReservationId],
      [IDL.Opt(Reservation)],
      ['query'],
    ),
  'getReservationsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getReservationsByTable' : IDL.Func(
      [TableId],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getRoom' : IDL.Func([RoomId], [IDL.Opt(Room)], ['query']),
  'getTable' : IDL.Func([TableId], [IDL.Opt(Table)], ['query']),
  'getTablesByRoom' : IDL.Func([RoomId], [IDL.Vec(Table)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMenuItem' : IDL.Func(
      [MenuItemId, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateReservation' : IDL.Func(
      [
        ReservationId,
        TableId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateRoom' : IDL.Func([RoomId, IDL.Text], [], []),
  'updateTable' : IDL.Func(
      [
        TableId,
        RoomId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MenuItemId = IDL.Nat;
  const TableId = IDL.Nat;
  const ReservationId = IDL.Nat;
  const RoomId = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Reservation = IDL.Record({
    'id' : ReservationId,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'tableId' : TableId,
    'notes' : IDL.Text,
    'partySize' : IDL.Nat,
  });
  const Room = IDL.Record({ 'id' : RoomId, 'name' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Table = IDL.Record({
    'id' : TableId,
    'height' : IDL.Float64,
    'posX' : IDL.Float64,
    'posY' : IDL.Float64,
    'shape' : IDL.Text,
    'capacity' : IDL.Nat,
    'roomId' : RoomId,
    'width' : IDL.Float64,
    'tableLabel' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Bool],
        [MenuItemId],
        [],
      ),
    'createReservation' : IDL.Func(
        [TableId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [ReservationId],
        [],
      ),
    'createRoom' : IDL.Func([IDL.Text], [RoomId], []),
    'createTable' : IDL.Func(
        [
          RoomId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [TableId],
        [],
      ),
    'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
    'deleteReservation' : IDL.Func([ReservationId], [], []),
    'deleteRoom' : IDL.Func([RoomId], [], []),
    'deleteTable' : IDL.Func([TableId], [], []),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getReservation' : IDL.Func(
        [ReservationId],
        [IDL.Opt(Reservation)],
        ['query'],
      ),
    'getReservationsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getReservationsByTable' : IDL.Func(
        [TableId],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getRoom' : IDL.Func([RoomId], [IDL.Opt(Room)], ['query']),
    'getTable' : IDL.Func([TableId], [IDL.Opt(Table)], ['query']),
    'getTablesByRoom' : IDL.Func([RoomId], [IDL.Vec(Table)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMenuItem' : IDL.Func(
        [MenuItemId, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateReservation' : IDL.Func(
        [
          ReservationId,
          TableId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateRoom' : IDL.Func([RoomId, IDL.Text], [], []),
    'updateTable' : IDL.Func(
        [
          TableId,
          RoomId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };